### ISSUE TITLE
能否说一下如何编译固件

### ISSUE THREAD

**Issue by fantasyjqc** [killadm/LOCK2MQTT#1]
您好，我使用了一下您的固件，可以正常输出，但是因为我有三把门锁以及其他一些蓝牙设备，所以希望对源码进行一些修改然后编译，但是发现无论如何自己编译的都无法使用，能否给一下编译的步骤以及使用的包版本吗，是用Arduino编译嘛？

![image](https://user-images.githubusercontent.com/4988150/81316712-80f5cd80-90be-11ea-807a-744aff61ee15.png)

**Comment by zhujunsan** [comment]
我自己编译了一下，无非是装一些依赖包就可以了
